### ISSUE TITLE
TORGMHとTOSの互換性について

### ISSUE THREAD

**Issue by Shanpan2** [reitou-mugicha/TownOfSuper#2]
初Issue失礼します。いつもTOSを使わせていただいており、感謝しています。
今回のAmong UsのV2022.10.25のアップデートにおきまして、TORGMHmodのv2022.10.21(公式アプデの仮対応でありテスト版)とTOSmodのv1.30でチャットが使えなくなるというバグが発生したので報告しておきたいと思いIssueを立ててきました。
TORGMHの問題ではないということらしいので出来れば修正のほうをお願いします。

[

https://user-images.githubusercontent.com/113867056/197314937-6750060b-27f0-4fac-8f93-b7f9858acfe5.mp4

](url)

**Comment by Shanpan2** [comment]
[https://user-images.githubusercontent.com/113867056/197312129-33d5e559-dbc7-4f39-b417-9c63e6ee46bc.mp4
](url)

**Comment by reitou-mugicha** [comment]
10.25版を今リリースしました。
TORGM-Hとの互換性も確認したので最新版の使用をお願いします。

**Comment by reitou-mugicha** [comment]
https://github.com/reitou-mugicha/TownOfSuper/releases/tag/1.3.1
こちらです
